server:
  port: 8080
  servlet:
    contextPath: /

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: exercice-api
  datasource:
    url: jdbc:postgresql://localhost:5432/exercicedb
    username: postgres
    password: Atunaracity99.
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    url: /openapi.yaml
  api-docs:
    enabled: true

wiremock:
  port: 8081
  base-url: http://localhost:8081
  mappings:
    directory: \src\main\resources

